name: flutter-ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze | tee flutter_analyze.txt
      - run: flutter test --reporter expanded | tee flutter_test.txt
      - name: Build Web (optional)
        run: flutter build web --release | tee flutter_build_web.txt
      - uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            flutter_analyze.txt
            flutter_test.txt
            flutter_build_web.txt
